# Generated by Django 5.1.4 on 2025-01-16 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peertutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
