# Generated by Django 5.1.4 on 2025-01-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('found_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
